/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/checker/wrangler.automatic.jsonc --include-runtime=false --env-interface=AutomaticEnv apps/checker/automatic-env.d.ts` (hash: 339c5ac34a2c30eb6c063de142422770)
interface __BaseEnv_AutomaticEnv {
  JOBS: D1Database;
  AUTOMATIC_ENABLED: 'false';
  AUTOMATIC_VALIDATION_ID: '';
  AUTOMATIC_WINDOW_USD: '4.5';
  AUTOMATIC_JOB_USD: '3';
  AUTOMATIC_RUN_USD: '0.1';
  AUTOMATIC_RESERVE_USD: '0.5';
  APIFY_TOKEN: string;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_AutomaticEnv {}
}
interface AutomaticEnv extends __BaseEnv_AutomaticEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'AUTOMATIC_ENABLED'
      | 'AUTOMATIC_VALIDATION_ID'
      | 'AUTOMATIC_WINDOW_USD'
      | 'AUTOMATIC_JOB_USD'
      | 'AUTOMATIC_RUN_USD'
      | 'AUTOMATIC_RESERVE_USD'
      | 'APIFY_TOKEN'
    >
  > {}
}
